# Generated by Django 2.2.6 on 2019-10-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='codigoFrequentador',
            new_name='codigoCategoria',
        ),
    ]
