# Generated by Django 2.2.6 on 2019-10-18 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_auto_20191018_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigoProduto', models.AutoField(primary_key=True, serialize=False)),
                ('precoCompra', models.FloatField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('precoVenda', models.FloatField(null=True)),
                ('qtde', models.IntegerField(null=True)),
                ('fornecedor', models.CharField(max_length=50)),
                ('fkCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
            ],
        ),
    ]
