# Generated by Django 2.2.4 on 2019-10-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dataCompra',
            field=models.DateField(null=True),
        ),
    ]
